accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

auctionit/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('auctions/', include('auctions.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'auctions'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('profile/setup/', views.editProfile, name='editProfile'),
    path('item/<int:item_pk>/', views.item, name='item'),
    path('codes/', views.codes, name='codes'), 
    path('explore/', views.explore, name='explore'),
    path('live/', views.live, name='live'),
    path('winners/', views.winners, name='winners'),
    # path('join_auction/', views.join_auction, name='join_auction'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  {% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'auctions/css/style.css' %}" media="screen">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  {% block head %}
  {% endblock %}
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/forms.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Forms Template{% endblock %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
    <div class="container container-forms">
        <div class="m-4">
            <img src="{% static 'auctions/images/logo/logo-med.png' %}" class="mx-auto d-block img-fluid">
        </div>
        <div class="container-forms-bordered">
            <div class="m-4">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3 class="text-center">{% block header %}Header{% endblock %}</h3>
                    <p class="text-center">{% block headerText %}{% endblock %}</p>

                    {% block errorMessage %}
                    {% if form.errors %}
                        <div class="alert alert-warning">
                            <strong>Error upon submission</strong><br> Please verify your entries
                        </div>
                    {% endif %}
                    {% endblock %}

                    {% block formContent %}

                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}

                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {% render_field field class="form-control" %}
                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}

                    {% endblock %}

                    <div class="mt-5">
                        <button type="submit" class="btn btn-block active">{% block submitBtnText %}Submit{% endblock %}</button>
                        <p class="text-center small">{% block submitBtnSubtext %}{% endblock %}</p>
                    </div>

                    {% block alternateInput %}
                    {% endblock %}
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function(){
            $('.toast').toast('show');
        });
    </script>
{% endblock %}

templates/navbar.html
<!-- templates/navbar.html -->
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block content %}
    {% load static %} 
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light" style="padding-left: 0px; padding-right: 0px;">
            <a class="navbar-brand" href="{% url 'auctions:profile' %}"><img src="{% static 'auctions/images/logo/logo-med.png' %}" style="height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <!-- Right aligned -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:profile' %}" >Profile</a>
                    </li>

                    {% if request.user.is_superuser %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
                            Admin
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Site</a>
                            <a class="dropdown-item" href="{% url 'auctions:winners' %}">Winners List</a>
                        </div>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:explore' %}">Explore</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:live' %}">Go Live</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>

                <!-- Left aligned -->
                <!-- TODO: Add a search component -->
                <form class="form-inline ml-auto" method="post" action="{% url 'auctions:explore' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn active" type="submit" href="{$ url 'auctions:explore' %}">Search</button>
                </form>
            </div>
        </nav>
    </div>
    <hr style="margin: -4px;" />

    {% block body %}
    {% endblock %}

{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'forms.html' %}

{% block title %}Sign Up{% endblock %}

{% block header %}Sign up{% endblock %}
{% block headerText %}One account, unlimited auctions{% endblock %}

{% block submitBtnText %}Sign up{% endblock %}
{% block submitBtnSubtext %}
    By clicking Sign up, you agree to our 
    <br>Terms and have read and acknowledge our 
    <br>Privacy Statement.
{% endblock %}